A new home
vapor/website pull request #112
Opened 2024-06-18 20:39 UTC by ptoffy

2024-06-20 00:14 UTC, 0xTim commented on stack.yml
We still want this since the stack is the same

2024-06-20 00:14 UTC, 0xTim commented on README.md
Keep the README with updates

2024-06-20 00:14 UTC, 0xTim commented on Package.swift
> +// swift-tools-version:5.5
Bump this to 5.10

2024-07-13 19:38 UTC, MahdiBM reviewed
Nice deployment preview we have there.
Looks good.
One inaccuracy is that @gwynne pruned a lot of the Discord members so users inactive past 1 month or something (at that time) got kicked and we now have only 4K members.

Though the "online members" number is still the same and the ratio should be even higher ... so maybe we could focus on that "online members" number.

2024-07-15 11:00 UTC, 0xTim requested changes
Some things I've noticed:

* Leaf link points to 4.0 we should fix that
* The compiler error has a `*` - I think it should be `'`
* The showcase section links aren't implemented. See full list should point to the showcase page for example and the scroll buttons I'm assuming don't work as we don't have any more to show? (They work on mobile)
* Become a supporter link does nothing
* The sponsors section on mobile is cut off, we should show the scroll buttons below a certain size or wrap them in a flex box so they're on different lines (can't remember what the design had)

Looking great though!

2024-07-15 11:00 UTC, 0xTim commented on Resources/static/js/scrollNavbar.js
Does this script not live in the design repo?

2024-07-15 11:00 UTC, 0xTim commented on Sources/Website/ComingSoonPage.swift
> +                app.get("showcase") { req in
```suggestion
                app.get("\(title.lowercase)") { req in
```

2024-07-15 14:28 UTC, ptoffy commented on Resources/static/js/scrollNavbar.js
It does but I wanted to bring in all the scripts we use on the main site over here. I can just point it to the design if you prefer, but now if we need to change something we don't need to do it there

2024-07-15 14:45 UTC, 0xTim commented on Resources/static/js/scrollNavbar.js
Ah yeah fair, we won't use this on other sites so it's all fine

2024-07-17 17:42 UTC, 0xTim approved these changes
Looks good to go! Just need to fix the showcase link

2024-07-17 18:40 UTC, merged